perl-Compress-Zlib is not needed
perl-Compress-Zlib causes conflicts during installation if a new errata is also applied. Quoting Orlin:
I'm having a problem installing WNs with SL 6.4 when the latest errata is used.

Basically the default version of perl-Compress-Zlib for SL6.4 which is used by Quattor during installation is 129.el6.x86_64.

The problem is that if errata 20130426 is used the kickstart tries to force installation of:

perl-Compress-Zlib-0:2.020-130.el6_4.x86_64

As other version of Perl is already installed on the WNs there are dependency issues & conflicts:

error: Failed dependencies:
>         perl = 4:5.10.1-130.el6_4 is needed by
> perl-Compress-Zlib-0:2.020-130.el6_4.x86_64
> Quattor installation on  failed: Failed to install
> perl-Compress-Zlib-2.020-130.el6_4.x86_64.rpm: 1

The workaround which fixes this issue is removing
perl-Compress-Zlib-0:2.020-130.el6_4.x86_64 from the kickstart as version 129.el6.x86_64 is already installed with all required dependencies.

SPMA upgrades all Perl packages to version 130.el6_4.x86_64 after the first reboot.

We installed at RAL both SL6 and SL5 systems without it and they worked fine, while SL6 systems were failing before.